import type { ForumCommentRecord, ForumPostRecord } from '@/lib/workspace-db';

export const forumSeedPosts: ForumPostRecord[] = [
  {
    id: 'seed-post-en-001',
    locale: 'en',
    author: 'CareerWatcher',
    title: 'What actually makes a student resume look employable in 2026?',
    content:
      'After reviewing dozens of student resumes, the pattern is clear. Recruiters do not need a long list of classes. They need evidence. One project with a strong problem statement, clear ownership, measurable outcome, and a short technical explanation beats five vague bullet lists. If your resume still reads like coursework, the problem is not formatting first. It is lack of proof.',
    category: 'Job Discussion',
    tags: 'resume,job-search,positioning',
    target_job: 'Software Engineer',
    company: '',
    views: 1840,
    likes: 142,
    comments_count: 2,
    created_at: '2026-05-01T10:15:00Z',
  },
  {
    id: 'seed-post-en-002',
    locale: 'en',
    author: 'MLDepth',
    title: 'A realistic 8-week roadmap for breaking into applied AI roles',
    content:
      'If you are targeting applied AI instead of pure research, you do not need to start with a dozen papers. You need one usable stack. My suggested eight-week plan is simple. Build one data pipeline, one training pipeline, one evaluation report, and one deployable demo. That portfolio shape is more convincing than scattered Kaggle notebooks.',
    category: 'Study Check-in',
    tags: 'ai,study-plan,portfolio',
    target_job: 'Applied AI Engineer',
    company: '',
    views: 1324,
    likes: 119,
    comments_count: 1,
    created_at: '2026-04-30T08:20:00Z',
  },
  {
    id: 'seed-post-en-003',
    locale: 'en',
    author: 'BackendNotes',
    title: 'ByteDance backend interview notes: what they pushed on beyond Java syntax',
    content:
      'The interesting part of the interview was not language trivia. They kept pushing on tradeoffs. Why this cache strategy. Why this database index. Why this retry policy. If you are preparing for backend interviews, stop memorizing isolated facts and start practicing explanation under constraints.',
    category: 'Interview Experience',
    tags: 'backend,interview,java,system-design',
    target_job: 'Backend Engineer',
    company: 'ByteDance',
    views: 2102,
    likes: 166,
    comments_count: 2,
    created_at: '2026-04-29T16:10:00Z',
  },
  {
    id: 'seed-post-en-004',
    locale: 'en',
    author: 'PMCandidate',
    title: 'Product manager students: stop writing “good communication” and show decision quality',
    content:
      'A student PM resume often fails because it sounds too self-evaluative. Instead of saying you are thoughtful or communicative, show how you framed a user problem, what options you considered, what metric you used, and how the decision changed after evidence. Hiring teams trust decision traces more than personality claims.',
    category: 'Job Help',
    tags: 'product,resume,storytelling',
    target_job: 'Product Manager',
    company: '',
    views: 954,
    likes: 77,
    comments_count: 1,
    created_at: '2026-04-28T13:00:00Z',
  },
  {
    id: 'seed-post-en-005',
    locale: 'en',
    author: 'SystemsFirst',
    title: 'Remote roles are not easier roles. They simply filter for different discipline.',
    content:
      'Students often assume remote roles are easier to get because geography disappears. In practice, remote roles usually screen harder for written clarity, self-management, and visible evidence of ownership. If you are applying remote, polish async communication and your portfolio explanation just as much as your coding.',
    category: 'Job Discussion',
    tags: 'remote,career,communication',
    target_job: '',
    company: '',
    views: 876,
    likes: 68,
    comments_count: 0,
    created_at: '2026-04-27T20:45:00Z',
  },
  {
    id: 'seed-post-en-006',
    locale: 'en',
    author: 'DesignSignal',
    title: 'Three mistakes that make junior product design portfolios feel generic',
    content:
      'The first mistake is showing polished screens without decision context. The second is hiding constraints. The third is making every project look visually similar. A strong junior design portfolio does not need huge breadth. It needs one or two cases where your reasoning is visible and your process feels honest.',
    category: 'Job Help',
    tags: 'design,portfolio,junior',
    target_job: 'Product Designer',
    company: '',
    views: 742,
    likes: 59,
    comments_count: 1,
    created_at: '2026-04-27T09:30:00Z',
  },
  {
    id: 'seed-post-en-007',
    locale: 'en',
    author: 'OfferDebrief',
    title: 'How I compared two offers when one had a bigger brand and the other had better scope',
    content:
      'I forced the decision into five lenses: manager quality, project scope, learning slope, compensation, and downside risk. Brand mattered, but only after I scored the role itself. The smaller company won because the work was closer to what I wanted to become good at. A famous logo is useful, but weak scope compounds badly in the first two years.',
    category: 'Job Discussion',
    tags: 'offer,decision-making,career',
    target_job: '',
    company: '',
    views: 1183,
    likes: 104,
    comments_count: 2,
    created_at: '2026-04-26T18:00:00Z',
  },
  {
    id: 'seed-post-en-008',
    locale: 'en',
    author: 'TestCraft',
    title: 'QA interview takeaway: they cared more about bug thinking than tool names',
    content:
      'The interviewer barely cared that I used Playwright instead of Cypress. What mattered was whether I could design coverage, isolate failure points, and explain why a bug would matter to users or the business. Tool names are easy to swap. Testing judgment is the actual signal.',
    category: 'Interview Experience',
    tags: 'qa,testing,interview',
    target_job: 'QA Engineer',
    company: '',
    views: 638,
    likes: 53,
    comments_count: 0,
    created_at: '2026-04-25T11:40:00Z',
  },
  {
    id: 'seed-post-en-009',
    locale: 'en',
    author: 'GrowthOps',
    title: 'Operations candidates need metrics stories, not activity stories',
    content:
      'Many operations resumes read like a schedule of tasks. Planned campaign. Managed community. Published content. The stronger version shows leverage. Improved retention by how much. Increased conversion from which step to which step. Reduced response time through what process change. Metrics make operations work legible.',
    category: 'Job Help',
    tags: 'operations,growth,resume',
    target_job: 'Operations Specialist',
    company: '',
    views: 712,
    likes: 65,
    comments_count: 1,
    created_at: '2026-04-25T08:10:00Z',
  },
  {
    id: 'seed-post-en-010',
    locale: 'en',
    author: 'DataNorth',
    title: 'Why student data projects often fail to impress hiring managers',
    content:
      'Because they stop at charts. A decent data project should show problem framing, dataset assumptions, cleaning logic, metric choice, and what decision could follow from the analysis. If your project only says “I visualized trends,” it still sounds like classwork.',
    category: 'Study Check-in',
    tags: 'data,analytics,projects',
    target_job: 'Data Analyst',
    company: '',
    views: 996,
    likes: 88,
    comments_count: 1,
    created_at: '2026-04-24T14:20:00Z',
  },
];

export const forumSeedComments: ForumCommentRecord[] = [
  {
    id: 'seed-comment-en-001',
    post_id: 'seed-post-en-001',
    locale: 'en',
    author: 'ResumeReview',
    content: 'This matches what I see too. Students underestimate how much quantified ownership changes perception.',
    likes: 12,
    created_at: '2026-05-01T11:20:00Z',
  },
  {
    id: 'seed-comment-en-002',
    post_id: 'seed-post-en-001',
    locale: 'en',
    author: 'NewGradLena',
    content: 'The “coursework tone” point hurts because it is true. I need to rewrite my bullets around outcomes.',
    likes: 9,
    created_at: '2026-05-01T12:05:00Z',
  },
  {
    id: 'seed-comment-en-003',
    post_id: 'seed-post-en-003',
    locale: 'en',
    author: 'InfraPrep',
    content: 'This is the best backend interview advice. Tradeoff explanation matters way more than memorized definitions.',
    likes: 14,
    created_at: '2026-04-29T17:10:00Z',
  },
  {
    id: 'seed-comment-en-004',
    post_id: 'seed-post-en-004',
    locale: 'en',
    author: 'PMIntern',
    content: 'Decision traces is a great phrase. I wish more PM prep content framed it that way.',
    likes: 8,
    created_at: '2026-04-28T15:14:00Z',
  },
  {
    id: 'seed-comment-en-005',
    post_id: 'seed-post-en-007',
    locale: 'en',
    author: 'OfferMath',
    content: 'Manager quality is so underrated when students compare offers. It can completely change the first year.',
    likes: 11,
    created_at: '2026-04-26T20:00:00Z',
  },
  {
    id: 'seed-comment-en-006',
    post_id: 'seed-post-en-010',
    locale: 'en',
    author: 'DataStarter',
    content: 'This explains why my old project looked weak. I had charts but no decision story behind them.',
    likes: 7,
    created_at: '2026-04-24T15:30:00Z',
  },
];
