import type { ForumCommentRecord, ForumPostRecord } from '@/lib/workspace-db';

export const forumSeedPosts: ForumPostRecord[] = [
  {
    id: 'seed-post-en-001',
    locale: 'en',
    author: 'CareerWatcher',
    title: 'What actually makes a student resume look employable in 2026?',
    content:
      'After reviewing dozens of student resumes, the pattern is clear. Recruiters do not need a long list of classes. They need evidence. One project with a strong problem statement, clear ownership, measurable outcome, and a short technical explanation beats five vague bullet lists. If your resume still reads like coursework, the problem is not formatting first. It is lack of proof.',
    category: 'Job Discussion',
    tags: 'resume,job-search,positioning',
    target_job: 'Software Engineer',
    company: '',
    views: 1840,
    likes: 142,
    comments_count: 2,
    created_at: '2026-05-01T10:15:00Z',
  },
  {
    id: 'seed-post-en-002',
    locale: 'en',
    author: 'MLDepth',
    title: 'A realistic 8-week roadmap for breaking into applied AI roles',
    content:
      'If you are targeting applied AI instead of pure research, you do not need to start with a dozen papers. You need one usable stack. My suggested eight-week plan is simple. Build one data pipeline, one training pipeline, one evaluation report, and one deployable demo. That portfolio shape is more convincing than scattered Kaggle notebooks.',
    category: 'Study Check-in',
    tags: 'ai,study-plan,portfolio',
    target_job: 'Applied AI Engineer',
    company: '',
    views: 1324,
    likes: 119,
    comments_count: 1,
    created_at: '2026-04-30T08:20:00Z',
  },
  {
    id: 'seed-post-en-003',
    locale: 'en',
    author: 'BackendNotes',
    title: 'ByteDance backend interview notes: what they pushed on beyond Java syntax',
    content:
      'The interesting part of the interview was not language trivia. They kept pushing on tradeoffs. Why this cache strategy. Why this database index. Why this retry policy. If you are preparing for backend interviews, stop memorizing isolated facts and start practicing explanation under constraints.',
    category: 'Interview Experience',
    tags: 'backend,interview,java,system-design',
    target_job: 'Backend Engineer',
    company: 'ByteDance',
    views: 2102,
    likes: 166,
    comments_count: 2,
    created_at: '2026-04-29T16:10:00Z',
  },
  {
    id: 'seed-post-en-004',
    locale: 'en',
    author: 'PMCandidate',
    title: 'Product manager students: stop writing “good communication” and show decision quality',
    content:
      'A student PM resume often fails because it sounds too self-evaluative. Instead of saying you are thoughtful or communicative, show how you framed a user problem, what options you considered, what metric you used, and how the decision changed after evidence. Hiring teams trust decision traces more than personality claims.',
    category: 'Job Help',
    tags: 'product,resume,storytelling',
    target_job: 'Product Manager',
    company: '',
    views: 954,
    likes: 77,
    comments_count: 1,
    created_at: '2026-04-28T13:00:00Z',
  },
  {
    id: 'seed-post-en-005',
    locale: 'en',
    author: 'SystemsFirst',
    title: 'Remote roles are not easier roles. They simply filter for different discipline.',
    content:
      'Students often assume remote roles are easier to get because geography disappears. In practice, remote roles usually screen harder for written clarity, self-management, and visible evidence of ownership. If you are applying remote, polish async communication and your portfolio explanation just as much as your coding.',
    category: 'Job Discussion',
    tags: 'remote,career,communication',
    target_job: '',
    company: '',
    views: 876,
    likes: 68,
    comments_count: 0,
    created_at: '2026-04-27T20:45:00Z',
  },
  {
    id: 'seed-post-en-006',
    locale: 'en',
    author: 'DesignSignal',
    title: 'Three mistakes that make junior product design portfolios feel generic',
    content:
      'The first mistake is showing polished screens without decision context. The second is hiding constraints. The third is making every project look visually similar. A strong junior design portfolio does not need huge breadth. It needs one or two cases where your reasoning is visible and your process feels honest.',
    category: 'Job Help',
    tags: 'design,portfolio,junior',
    target_job: 'Product Designer',
    company: '',
    views: 742,
    likes: 59,
    comments_count: 1,
    created_at: '2026-04-27T09:30:00Z',
  },
  {
    id: 'seed-post-en-007',
    locale: 'en',
    author: 'OfferDebrief',
    title: 'How I compared two offers when one had a bigger brand and the other had better scope',
    content:
      'I forced the decision into five lenses: manager quality, project scope, learning slope, compensation, and downside risk. Brand mattered, but only after I scored the role itself. The smaller company won because the work was closer to what I wanted to become good at. A famous logo is useful, but weak scope compounds badly in the first two years.',
    category: 'Job Discussion',
    tags: 'offer,decision-making,career',
    target_job: '',
    company: '',
    views: 1183,
    likes: 104,
    comments_count: 2,
    created_at: '2026-04-26T18:00:00Z',
  },
  {
    id: 'seed-post-en-008',
    locale: 'en',
    author: 'TestCraft',
    title: 'QA interview takeaway: they cared more about bug thinking than tool names',
    content:
      'The interviewer barely cared that I used Playwright instead of Cypress. What mattered was whether I could design coverage, isolate failure points, and explain why a bug would matter to users or the business. Tool names are easy to swap. Testing judgment is the actual signal.',
    category: 'Interview Experience',
    tags: 'qa,testing,interview',
    target_job: 'QA Engineer',
    company: '',
    views: 638,
    likes: 53,
    comments_count: 0,
    created_at: '2026-04-25T11:40:00Z',
  },
  {
    id: 'seed-post-en-009',
    locale: 'en',
    author: 'GrowthOps',
    title: 'Operations candidates need metrics stories, not activity stories',
    content:
      'Many operations resumes read like a schedule of tasks. Planned campaign. Managed community. Published content. The stronger version shows leverage. Improved retention by how much. Increased conversion from which step to which step. Reduced response time through what process change. Metrics make operations work legible.',
    category: 'Job Help',
    tags: 'operations,growth,resume',
    target_job: 'Operations Specialist',
    company: '',
    views: 712,
    likes: 65,
    comments_count: 1,
    created_at: '2026-04-25T08:10:00Z',
  },
  {
    id: 'seed-post-en-010',
    locale: 'en',
    author: 'DataNorth',
    title: 'Why student data projects often fail to impress hiring managers',
    content:
      'Because they stop at charts. A decent data project should show problem framing, dataset assumptions, cleaning logic, metric choice, and what decision could follow from the analysis. If your project only says “I visualized trends,” it still sounds like classwork.',
    category: 'Study Check-in',
    tags: 'data,analytics,projects',
    target_job: 'Data Analyst',
    company: '',
    views: 996,
    likes: 88,
    comments_count: 1,
    created_at: '2026-04-24T14:20:00Z',
  },
  {
    id: 'seed-post-zh-001',
    locale: 'zh',
    author: '简历复盘员',
    title: '应届生简历最容易被忽略的问题：没有证据链',
    content:
      '很多同学的简历不是内容少，而是证据太弱。比如写“熟悉 React”，不如写清楚你做过什么页面、解决了什么性能或交互问题、最终指标有没有变化。招聘方真正想看的不是你学过什么，而是你能把什么事情做成。',
    category: 'Job Help',
    tags: '简历,应届生,求职',
    target_job: 'Frontend Engineer',
    company: '',
    views: 1260,
    likes: 98,
    comments_count: 2,
    created_at: '2026-05-02T09:00:00Z',
  },
  {
    id: 'seed-post-zh-002',
    locale: 'zh',
    author: '后端面经整理',
    title: '后端面试里，为什么系统设计比八股更容易拉开差距',
    content:
      '八股题能帮你过基础筛选，但真正拉开差距的是你能不能解释取舍。为什么要加缓存，缓存失效怎么办，数据库索引为什么这样建，接口失败后怎么重试。面试官想看到的是你能不能在约束下做判断。',
    category: 'Interview Experience',
    tags: '后端,系统设计,面试',
    target_job: 'Backend Engineer',
    company: 'ByteDance',
    views: 1834,
    likes: 151,
    comments_count: 2,
    created_at: '2026-05-01T15:20:00Z',
  },
  {
    id: 'seed-post-zh-003',
    locale: 'zh',
    author: 'AI转岗记录',
    title: '想投应用 AI 岗位，不要只堆论文，先做一个能跑通的作品',
    content:
      '如果目标是应用 AI 或算法工程，不一定一开始就追求很深的研究成果。更现实的路径是做一个端到端作品：数据处理、模型调用或训练、评估指标、简单部署和复盘报告。能跑通、能解释、能迭代，比零散 notebook 更有说服力。',
    category: 'Study Check-in',
    tags: 'AI,项目,作品集',
    target_job: 'Machine Learning Engineer',
    company: '',
    views: 1098,
    likes: 87,
    comments_count: 1,
    created_at: '2026-04-30T12:30:00Z',
  },
  {
    id: 'seed-post-zh-004',
    locale: 'zh',
    author: '产品实习观察',
    title: '产品岗学生不要只写“沟通能力强”，要写决策过程',
    content:
      '产品简历里最常见的问题是太像自我评价。与其写沟通能力强，不如写你如何发现问题、比较了哪些方案、用了什么指标判断结果、最后如何调整。产品岗最有价值的证据是决策质量，而不是形容词。',
    category: 'Job Discussion',
    tags: '产品,实习,简历',
    target_job: 'Product Manager',
    company: '',
    views: 854,
    likes: 74,
    comments_count: 1,
    created_at: '2026-04-29T10:10:00Z',
  },
  {
    id: 'seed-post-zh-005',
    locale: 'zh',
    author: '数据分析同学',
    title: '数据分析项目不要停在画图，必须能导向一个决策',
    content:
      '很多数据项目的问题是只有图表，没有业务问题。一个更完整的项目应该包含问题背景、数据假设、清洗逻辑、指标选择、分析结论和下一步决策。如果只是展示趋势，面试官很难判断你是否真的能支持业务。',
    category: 'Study Check-in',
    tags: '数据分析,SQL,项目',
    target_job: 'Data Analyst',
    company: '',
    views: 923,
    likes: 81,
    comments_count: 1,
    created_at: '2026-04-28T18:40:00Z',
  },
];

export const forumSeedComments: ForumCommentRecord[] = [
  {
    id: 'seed-comment-en-001',
    post_id: 'seed-post-en-001',
    locale: 'en',
    author: 'ResumeReview',
    content: 'This matches what I see too. Students underestimate how much quantified ownership changes perception.',
    likes: 12,
    created_at: '2026-05-01T11:20:00Z',
  },
  {
    id: 'seed-comment-en-002',
    post_id: 'seed-post-en-001',
    locale: 'en',
    author: 'NewGradLena',
    content: 'The “coursework tone” point hurts because it is true. I need to rewrite my bullets around outcomes.',
    likes: 9,
    created_at: '2026-05-01T12:05:00Z',
  },
  {
    id: 'seed-comment-en-003',
    post_id: 'seed-post-en-003',
    locale: 'en',
    author: 'InfraPrep',
    content: 'This is the best backend interview advice. Tradeoff explanation matters way more than memorized definitions.',
    likes: 14,
    created_at: '2026-04-29T17:10:00Z',
  },
  {
    id: 'seed-comment-en-004',
    post_id: 'seed-post-en-004',
    locale: 'en',
    author: 'PMIntern',
    content: 'Decision traces is a great phrase. I wish more PM prep content framed it that way.',
    likes: 8,
    created_at: '2026-04-28T15:14:00Z',
  },
  {
    id: 'seed-comment-en-005',
    post_id: 'seed-post-en-007',
    locale: 'en',
    author: 'OfferMath',
    content: 'Manager quality is so underrated when students compare offers. It can completely change the first year.',
    likes: 11,
    created_at: '2026-04-26T20:00:00Z',
  },
  {
    id: 'seed-comment-en-006',
    post_id: 'seed-post-en-010',
    locale: 'en',
    author: 'DataStarter',
    content: 'This explains why my old project looked weak. I had charts but no decision story behind them.',
    likes: 7,
    created_at: '2026-04-24T15:30:00Z',
  },
  {
    id: 'seed-comment-zh-001',
    post_id: 'seed-post-zh-001',
    locale: 'zh',
    author: '前端准备中',
    content: '证据链这个说法很准确，我之前的项目描述确实太像课程作业了。',
    likes: 8,
    created_at: '2026-05-02T10:15:00Z',
  },
  {
    id: 'seed-comment-zh-002',
    post_id: 'seed-post-zh-001',
    locale: 'zh',
    author: '求改简历',
    content: '如果没有线上指标，是不是可以写性能优化前后的本地测试数据？',
    likes: 6,
    created_at: '2026-05-02T11:00:00Z',
  },
  {
    id: 'seed-comment-zh-003',
    post_id: 'seed-post-zh-002',
    locale: 'zh',
    author: 'Java后端',
    content: '我面试也被追问过缓存一致性，确实不是背概念能解决的。',
    likes: 10,
    created_at: '2026-05-01T16:30:00Z',
  },
  {
    id: 'seed-comment-zh-004',
    post_id: 'seed-post-zh-003',
    locale: 'zh',
    author: 'ML入门',
    content: '端到端 demo 比单独模型训练更适合展示工程能力，这点很有用。',
    likes: 7,
    created_at: '2026-04-30T13:40:00Z',
  },
  {
    id: 'seed-comment-zh-005',
    post_id: 'seed-post-zh-004',
    locale: 'zh',
    author: 'PM实习生',
    content: '决策过程比“沟通能力强”更容易让人相信，准备按这个思路重写项目。',
    likes: 5,
    created_at: '2026-04-29T12:00:00Z',
  },
  {
    id: 'seed-comment-zh-006',
    post_id: 'seed-post-zh-005',
    locale: 'zh',
    author: '数据求职',
    content: '我的项目确实只有 dashboard，没有写最后支持了什么判断。',
    likes: 6,
    created_at: '2026-04-28T19:30:00Z',
  },
];
