export type SiteLocale = 'zh' | 'en';

export const siteContent = {
  zh: {
    home: {
      badge: 'AI 求职能力定位器',
      title: '先看清自己，再去投更合适的机会。',
      description:
        '够得着把对话评估、岗位样本、学习资源和互助社区放进同一条链路里，让大学生的求职准备更具体、更稳、更能执行。',
      primaryCta: '开始能力定位',
      secondaryCta: '查看职位库',
      metrics: [
        { value: '6', label: '能力维度' },
        { value: '21', label: '真实岗位样本' },
        { value: '60+', label: '学习资源' },
        { value: '1', label: '统一求职工作台' },
      ],
      workflow: [
        {
          title: '聊出你的能力画像',
          description: '不是填一堆表单，而是从项目、技能、实习和兴趣里梳理你真正的起点。',
        },
        {
          title: '把岗位差距看具体',
          description: '安全投递、可以冲、需要长期积累，三种判断一眼看明白。',
        },
        {
          title: '把准备动作拆成计划',
          description: '该补什么知识、该做什么项目、该先投什么机会，形成连续动作。',
        },
      ],
      pillars: [
        {
          title: '能力定位',
          description: '围绕技术、项目、沟通、行业认知、实习经历和学习潜力，形成更可信的起点判断。',
        },
        {
          title: '岗位浏览',
          description: '把字节、腾讯、阿里等岗位样本拉到同一个界面里筛选、收藏和对比。',
        },
        {
          title: '资源补课',
          description: '按前端、后端、算法、数据、产品、运营分方向整理学习材料。',
        },
        {
          title: '互助社区',
          description: '面经、求助、岗位讨论和学习打卡放在同一个社区流里，减少孤军作战。',
        },
      ],
      roleTracks: [
        '前端工程',
        '后端开发',
        '算法与数据',
        '产品与运营',
      ],
      ctaTitle: '如果你现在只知道“想找工作”，这已经足够开始。',
      ctaDescription:
        '从对话入口进入，你会先获得一个更清楚的自我判断，再决定怎么投、补什么、去哪里找支持。',
    },
    jobs: {
      heroTitle: '职位探索台',
      heroDescription: '从真实岗位样本里看方向、看门槛、看自己现在最该准备什么。',
      searchPlaceholder: '搜索岗位名、技能关键词、公司',
      searchButton: '搜索',
      allCompanies: '全部公司',
      allCategories: '全部方向',
      allTypes: '全部类型',
      totalLabel: '当前结果',
      emptyTitle: '没有找到符合条件的岗位',
      emptyDescription: '换一个关键词，或者放宽筛选条件再看一轮。',
      detailLabel: '查看详情',
      saved: '已收藏',
      save: '收藏',
    },
    forum: {
      heroTitle: '求职论坛',
      heroDescription: '把面经、岗位讨论、求助和学习打卡沉淀下来，形成同路人的经验池。',
      createButton: '发布帖子',
      createTitle: '写一条新帖子',
      titleLabel: '标题',
      companyLabel: '公司或场景',
      contentLabel: '正文',
      tagsLabel: '标签',
      submitButton: '发布',
      latest: '最新',
      hot: '热度',
      top: '高赞',
      emptyTitle: '这里还很安静',
      emptyDescription: '第一条帖子通常会比你想象中更有帮助。',
      myPost: '我的帖子',
      delete: '删除',
      deleting: '删除中…',
    },
    resources: {
      heroTitle: '资源中心',
      heroDescription: '不是堆链接，而是按目标方向把书、课和练习平台组织成能直接开做的素材库。',
      books: '书单',
      courses: '课程',
      practice: '练习平台',
      emptyTitle: '这个筛选下暂时没有资源',
      emptyDescription: '切换方向或资源类型试试看。',
    },
    profile: {
      heroTitle: '我的工作台',
      heroDescription: '把自己在站内的发帖、互动、收藏和投递准备集中起来看。',
      signOut: '退出登录',
      stats: {
        posts: '我的帖子',
        comments: '我的评论',
        likes: '点赞记录',
        received: '收到的赞',
      },
      sections: {
        posts: '最近发布',
        comments: '最近评论',
        liked: '赞过的帖子',
        jobs: '收藏职位',
        resources: '收藏资源',
      },
      empty: '还没有内容',
    },
  },
  en: {
    home: {
      badge: 'AI Career Positioning Studio',
      title: 'Understand your current edge before chasing the next role.',
      description:
        'Reachable connects guided assessment, job samples, learning resources, and peer support so students can prepare with more clarity and less drift.',
      primaryCta: 'Start Assessment',
      secondaryCta: 'Browse Jobs',
      metrics: [
        { value: '6', label: 'ability lenses' },
        { value: '21', label: 'job samples' },
        { value: '60+', label: 'learning resources' },
        { value: '1', label: 'career workspace' },
      ],
      workflow: [
        {
          title: 'Surface a realistic profile',
          description: 'Turn projects, skills, internships, and interests into a clearer baseline than a generic self-introduction.',
        },
        {
          title: 'See role gaps in plain terms',
          description: 'Separate safe bets, stretch options, and long-term targets without guessing in the dark.',
        },
        {
          title: 'Translate insight into action',
          description: 'Convert missing skills into concrete projects, resources, and next applications.',
        },
      ],
      pillars: [
        {
          title: 'Assessment',
          description: 'Review technical skills, project depth, communication, industry awareness, internships, and learning potential in one flow.',
        },
        {
          title: 'Job Browser',
          description: 'Filter, compare, and bookmark role samples from major companies in a single interface.',
        },
        {
          title: 'Resource System',
          description: 'Browse books, courses, and practice platforms by track: frontend, backend, data, algorithm, product, and operations.',
        },
        {
          title: 'Peer Forum',
          description: 'Interview notes, study logs, and job-seeking questions stay connected instead of scattered.',
        },
      ],
      roleTracks: [
        'Frontend engineering',
        'Backend systems',
        'Data and algorithms',
        'Product and operations',
      ],
      ctaTitle: 'If all you know is “I need a job soon”, that is enough to start.',
      ctaDescription:
        'Open the chat flow, get a sharper read on where you stand, and then decide what to apply for and what to build next.',
    },
    jobs: {
      heroTitle: 'Job Explorer',
      heroDescription: 'Browse real role samples to understand direction, bar, and what your preparation should optimize for.',
      searchPlaceholder: 'Search by role, skill, or company',
      searchButton: 'Search',
      allCompanies: 'All companies',
      allCategories: 'All tracks',
      allTypes: 'All types',
      totalLabel: 'Results',
      emptyTitle: 'No roles matched this filter',
      emptyDescription: 'Try a broader keyword or loosen one of the filters.',
      detailLabel: 'View details',
      saved: 'Saved',
      save: 'Save',
    },
    forum: {
      heroTitle: 'Career Forum',
      heroDescription: 'Keep interview notes, peer questions, study logs, and role discussions in one visible stream.',
      createButton: 'New Post',
      createTitle: 'Write a Post',
      titleLabel: 'Title',
      companyLabel: 'Company or context',
      contentLabel: 'Content',
      tagsLabel: 'Tags',
      submitButton: 'Publish',
      latest: 'Latest',
      hot: 'Hot',
      top: 'Top',
      emptyTitle: 'No posts yet',
      emptyDescription: 'The first useful post usually starts with one real question.',
      myPost: 'My Post',
      delete: 'Delete',
      deleting: 'Deleting…',
    },
    resources: {
      heroTitle: 'Resource Library',
      heroDescription: 'A cleaner system for books, courses, and practice links that actually maps to career tracks.',
      books: 'Books',
      courses: 'Courses',
      practice: 'Practice',
      emptyTitle: 'No resources in this filter',
      emptyDescription: 'Switch track or resource type to widen the pool.',
    },
    profile: {
      heroTitle: 'My Workspace',
      heroDescription: 'See your posts, interactions, saved roles, and study material in one account view.',
      signOut: 'Sign Out',
      stats: {
        posts: 'Posts',
        comments: 'Comments',
        likes: 'Liked posts',
        received: 'Likes received',
      },
      sections: {
        posts: 'Recent Posts',
        comments: 'Recent Comments',
        liked: 'Liked Posts',
        jobs: 'Saved Jobs',
        resources: 'Saved Resources',
      },
      empty: 'Nothing here yet',
    },
  },
} as const;
